Sc-75
engtech-projects/CHRRS-UI pull request #3
Opened 2023-05-22 08:24 UTC by mbunico

2023-05-22 08:30 UTC, janlofredy requested changes

2023-05-22 08:30 UTC, janlofredy commented on components/layout/JobsCard.vue
> +.description {
Don't use negative margins

2023-05-22 08:30 UTC, janlofredy commented on components/layout/JobsLike.vue
> +  border-bottom: 2px solid black;
use tailwind 
@apply border-b-2 border-black

2023-05-23 01:01 UTC, mbunico commented on components/layout/JobsCard.vue
> +.description {
fixed

2023-05-23 01:01 UTC, mbunico commented on components/layout/JobsLike.vue
> +  border-bottom: 2px solid black;
fixed

2023-05-23 05:32 UTC, janlofredy approved these changes

2023-05-23 05:32 UTC, merged